### ISSUE TITLE
please fix 

### ISSUE THREAD

**Issue by sajeeshab** [D35m0nd142/LFISuite#34]
/LFISuite/lfisuite.py", line 27
    print "[!] pipper not found in the current directory.. Downloading pipper.."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[!] pipper not found in the current directory.. Downloading pipper..")?

**Comment by JustMarfix** [comment]
Here is fix. Unfortunately, i can`t fix EVERY bug. But I fixed this one.

Fix: https://github.com/JustMarfix/LFISuiteFIX

**Comment by JustMarfix** [comment]
You need to install python2 and type in your terminal:
`python2 <path_to_lfisuite.py>`

**Comment by sajeeshab** [comment]
Installing module 'termcolor'
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: termcolor in /usr/lib/python3/dist-packages (1.1.0)
Traceback (most recent call last):
  File "lfisuite.py", line 68, in <module>
    from termcolor import colored
ImportError: No module named termcolor

**Comment by monikasharma47** [comment]
Showing this error

Traceback (most recent call last):
  File "lfisuite.py", line 50, in <module>
    import requests
ImportError: No module named requests

**Comment by slimamun** [comment]
File "lfisuite.py", line 50, in <module>
    import requests
ImportError: No module named requests

**Comment by ulises2k** [comment]
pip install requests

**Comment by sumonahmedku** [comment]
LFISuite/lfisuite.py", line 27
print "[!] pipper not found in the current directory.. Downloading pipper.."
^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("[!] pipper not found in the current directory.. Downloading pipper..")?

**Comment by ulises2k** [comment]
Edit the file by putting parentheses on it. I should stay.
print("[!] pipper not found in current directory... Downloading pipper...")

**Comment by 0xbitsnbytes** [comment]
Python3 is required, use 2 to 3 tools , To convert this tool to python3. Still Coding changing is required
